import { createServiceRoleClient } from '@/lib/supabase/service-role';
import { getPaymentApiEnv } from '@/lib/server/cf-env';
import { resendLifecycleDelivery, setLifecycleSuppression, toggleLifecycleTemplate, updateLifecyclePreference, updateLifecycleTemplate } from './actions';

export const dynamic = 'force-dynamic';
const input = 'w-full rounded-xl border border-outline-variant/30 bg-surface-container-lowest px-3 py-2 text-sm';
const button = 'rounded-xl bg-primary px-3 py-2 text-xs font-bold text-on-primary';

export default async function LifecycleEmailPage() {
  const env = await getPaymentApiEnv();
  const db = createServiceRoleClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);
  const [templatesResult, deliveriesResult, suppressionsResult] = await Promise.all([
    db.from('lifecycle_email_templates').select('*').order('template_key'),
    db.from('lifecycle_email_deliveries').select('id,created_at,recipient_email,template_key,status,attempts,max_attempts,last_error,provider_message_id').order('created_at', { ascending: false }).limit(100),
    db.from('lifecycle_email_suppressions').select('email,scope,reason,active,updated_at').eq('active', true).order('updated_at', { ascending: false }).limit(30),
  ]);
  const templates = templatesResult.data ?? []; const deliveries = deliveriesResult.data ?? []; const suppressions = suppressionsResult.data ?? [];
  const counts = deliveries.reduce<Record<string, number>>((a, d) => ({ ...a, [d.status]: (a[d.status] ?? 0) + 1 }), {});
  return <div className="space-y-6">
    <header><p className="text-xs font-bold uppercase tracking-widest text-on-surface-variant">Admin · Customer operations</p><h1 className="text-3xl font-black">Lifecycle email</h1><p className="text-sm text-on-surface-variant">Durable delivery, retries, provider evidence, preferences, and suppression in one control plane.</p></header>
    <section className="grid gap-3 sm:grid-cols-4">{['queued','retrying','failed','delivered'].map(s => <div key={s} className="rounded-2xl border border-outline-variant/25 bg-surface-container-lowest p-4"><p className="text-xs uppercase text-on-surface-variant">{s}</p><p className="text-3xl font-black">{counts[s] ?? 0}</p></div>)}</section>
    <section className="rounded-2xl border border-outline-variant/25 bg-surface-container-lowest p-5"><h2 className="text-lg font-bold">Templates and previews</h2><div className="mt-4 space-y-4">{templates.map(t => <details key={t.template_key} className="rounded-xl border border-outline-variant/20 p-4"><summary className="cursor-pointer font-bold">{t.template_key} <span className="text-xs font-normal text-on-surface-variant">· {t.category} · {t.enabled ? 'enabled' : 'disabled'}</span></summary><form action={updateLifecycleTemplate} className="mt-3 grid gap-3"><input type="hidden" name="template_key" value={t.template_key}/><label className="text-xs font-bold">Subject<input className={input} name="subject_template" defaultValue={t.subject_template}/></label><label className="text-xs font-bold">Body<textarea className={`${input} min-h-32`} name="body_template" defaultValue={t.body_template}/></label><div className="flex gap-2"><button className={button}>Save template</button></div></form><form action={toggleLifecycleTemplate} className="mt-2"><input type="hidden" name="template_key" value={t.template_key}/><input type="hidden" name="enabled" value={t.enabled ? 'false' : 'true'}/><button className="rounded-xl border px-3 py-2 text-xs font-bold">{t.enabled ? 'Disable' : 'Enable'}</button></form><div className="mt-3 rounded-xl bg-surface-container-low p-3 text-xs"><strong>Preview</strong><p className="mt-1">{t.subject_template}</p><p className="mt-2 whitespace-pre-wrap text-on-surface-variant">{t.body_template}</p></div></details>)}</div></section>
    <section className="rounded-2xl border border-outline-variant/25 bg-surface-container-lowest p-5"><h2 className="text-lg font-bold">Recent deliveries</h2><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr>{['Created','Recipient','Template','Status','Attempts','Error','Action'].map(h=><th key={h} className="p-2 text-xs uppercase text-on-surface-variant">{h}</th>)}</tr></thead><tbody>{deliveries.map(d=><tr key={d.id} className="border-t border-outline-variant/20"><td className="p-2">{new Date(d.created_at).toLocaleString()}</td><td className="p-2">{d.recipient_email}</td><td className="p-2">{d.template_key}</td><td className="p-2 font-bold">{d.status}</td><td className="p-2">{d.attempts}/{d.max_attempts}</td><td className="max-w-48 truncate p-2">{d.last_error ?? '—'}</td><td className="p-2"><form action={resendLifecycleDelivery}><input type="hidden" name="delivery_id" value={d.id}/><button className={button}>Resend</button></form></td></tr>)}</tbody></table></div></section>
    <section className="grid gap-4 lg:grid-cols-2"><form action={updateLifecyclePreference} className="rounded-2xl border border-outline-variant/25 bg-surface-container-lowest p-5"><h2 className="font-bold">Recipient preferences</h2><input className={`${input} mt-3`} name="email" type="email" placeholder="customer@business.com" required/><div className="mt-3 flex gap-4 text-sm"><label><input type="checkbox" name="transactional" value="true" defaultChecked/> Transactional</label><label><input type="checkbox" name="marketing" value="true" defaultChecked/> Marketing</label></div><button className={`${button} mt-3`}>Save preferences</button></form><form action={setLifecycleSuppression} className="rounded-2xl border border-outline-variant/25 bg-surface-container-lowest p-5"><h2 className="font-bold">Suppression control</h2><input className={`${input} mt-3`} name="email" type="email" placeholder="recipient@business.com" required/><div className="mt-3 flex gap-2"><select className={input} name="scope"><option value="all">All email</option><option value="marketing">Marketing only</option></select><select className={input} name="active"><option value="true">Suppress</option><option value="false">Unsuppress</option></select></div><button className={`${button} mt-3`}>Apply</button></form></section>
    {suppressions.length > 0 && <section className="rounded-2xl border border-outline-variant/25 p-5"><h2 className="font-bold">Active suppressions</h2><ul className="mt-2 text-sm">{suppressions.map(s=><li key={`${s.email}-${s.scope}`} className="border-t py-2">{s.email} · {s.scope} · {s.reason}</li>)}</ul></section>}
  </div>;
}
