/**
 * Turns Fix Agent output into a pull request on the customer's own repo.
 *
 * SAFETY POSTURE (deliberately conservative for v1):
 *   - Only ever writes to a NEW branch, never to the default branch.
 *   - Only CREATES standalone files it can place unambiguously (llms.txt, robots.txt) —
 *     it never rewrites existing application code it cannot parse.
 *   - Everything else ships as a reviewable checklist in GEO-PULSE-FIXES.md + the PR body,
 *     so a human applies the code-level edits.
 *   - Never merges. The customer reviews and merges.
 */
import type { AgentFix } from './fix-agent';
import { createBranch, createPullRequest, getDefaultBranch, putFile } from './github-app';

export type FixAgentPrResult =
  | { ok: true; url: string; number: number; filesWritten: string[] }
  | { ok: false; reason: string };

/**
 * If a fix is a whole standalone file we can place safely, return its path. Anything that edits
 * existing source returns null and stays a human checklist item.
 */
export function safeFilePathFor(fix: AgentFix): string | null {
  const hay = `${fix.where} ${fix.title}`.toLowerCase();
  if (hay.includes('llms.txt')) return 'public/llms.txt';
  if (hay.includes('robots.txt')) return 'public/robots.txt';
  if (hay.includes('security.txt')) return 'public/.well-known/security.txt';
  return null;
}

export function buildFixesMarkdown(domain: string, fixes: AgentFix[]): string {
  const lines: string[] = [
    `# GEO-Pulse — AI search readiness fixes for ${domain}`,
    '',
    'Generated by the GEO-Pulse **Fix Agent** from your latest audit. Each item below is the exact',
    'change to make. Files the agent could place safely are already committed in this PR; the rest',
    'are listed here for you to apply.',
    '',
  ];
  fixes.forEach((fix, i) => {
    const auto = safeFilePathFor(fix);
    lines.push(`## ${i + 1}. ${fix.title}`);
    if (fix.why) lines.push('', `_${fix.why}_`);
    if (fix.where) lines.push('', `**Where:** ${fix.where}`);
    lines.push('', auto ? `**Status:** committed to \`${auto}\` in this PR.` : '**Status:** apply manually.');
    lines.push('', '```', fix.snippet, '```', '');
  });
  return lines.join('\n');
}

function buildPrBody(domain: string, fixes: AgentFix[], written: string[]): string {
  const manual = fixes.filter((f) => !safeFilePathFor(f));
  const out: string[] = [
    '## 🤖 GEO-Pulse Fix Agent',
    '',
    `I audited **${domain}** and prepared ${fixes.length} fix${fixes.length === 1 ? '' : 'es'} to improve how AI answer engines crawl, understand and cite it.`,
    '',
  ];
  if (written.length > 0) {
    out.push('### Committed in this PR', ...written.map((p) => `- \`${p}\``), '');
  }
  if (manual.length > 0) {
    out.push(
      '### Needs your hands (edits existing code — I will not touch it)',
      ...manual.map((f) => `- **${f.title}**${f.where ? ` — _${f.where}_` : ''}`),
      '',
      'Full snippets are in `GEO-PULSE-FIXES.md`.',
      ''
    );
  }
  out.push('---', '', 'I only ever open PRs — I never merge or deploy. Review and merge when you are happy.');
  return out.join('\n');
}

export async function openFixAgentPr(args: {
  token: string;
  owner: string;
  repo: string;
  domain: string;
  fixes: AgentFix[];
  /** Injected for deterministic branch names in tests. */
  stamp?: string;
}): Promise<FixAgentPrResult> {
  const { token, owner, repo, domain, fixes } = args;
  if (fixes.length === 0) return { ok: false, reason: 'no_fixes' };

  const base = await getDefaultBranch(token, owner, repo);
  if (!base.ok) return { ok: false, reason: base.reason };

  const stamp = args.stamp ?? new Date().toISOString().replace(/[:.]/g, '-').slice(0, 16);
  const branch = `geo-pulse/fixes-${stamp}`;
  const made = await createBranch(token, owner, repo, branch, base.sha);
  if (!made.ok) return { ok: false, reason: made.reason ?? 'create_branch_failed' };

  const filesWritten: string[] = [];

  // 1) Standalone files we can place safely.
  for (const fix of fixes) {
    const path = safeFilePathFor(fix);
    if (!path) continue;
    const res = await putFile(token, owner, repo, branch, path, `${fix.snippet}\n`, `fix(geo-pulse): ${fix.title}`);
    if (res.ok) filesWritten.push(path);
  }

  // 2) The reviewable checklist — always written, so the PR is never empty.
  const mdPath = 'GEO-PULSE-FIXES.md';
  const md = await putFile(
    token,
    owner,
    repo,
    branch,
    mdPath,
    buildFixesMarkdown(domain, fixes),
    'docs(geo-pulse): AI search readiness fix list'
  );
  if (md.ok) filesWritten.push(mdPath);
  if (filesWritten.length === 0) return { ok: false, reason: 'nothing_written' };

  const pr = await createPullRequest(token, owner, repo, {
    title: `🤖 GEO-Pulse Fix Agent: ${fixes.length} AI-readiness fix${fixes.length === 1 ? '' : 'es'}`,
    head: branch,
    base: base.branch,
    body: buildPrBody(domain, fixes, filesWritten),
  });
  if (!pr.ok) return { ok: false, reason: pr.reason };

  return { ok: true, url: pr.url, number: pr.number, filesWritten };
}
