export function buildLayerOneReportRewritePrompt(args: {
  readonly reportMarkdown: string;
}): string {
  const reportMarkdown = args.reportMarkdown.trim();

  return [
    'You are rewriting a GEO-Pulse Layer One audit report.',
    '',
    'Your job is to produce a customer-safe rewrite of the report below.',
    'Do not add new facts.',
    'Do not invent market statistics, industry benchmarks, or unsupported 2026 claims.',
    'Do not turn weak signals into hard diagnosis.',
    'Do not present optional GEO ideas as mandatory remediation.',
    '',
    'Use this exact section order:',
    '1. Executive summary',
    '2. Confirmed audit findings',
    '3. Likely implications',
    '4. Priority actions',
    '5. Optional advanced GEO improvements',
    '6. Open questions and follow-up checks',
    '',
    'Section rules:',
    '- Confirmed audit findings: only state what the report directly supports.',
    '- Likely implications: use bounded wording such as "suggests", "may", "likely", or "needs verification".',
    '- Optional advanced GEO improvements: keep these clearly separate from required remediation.',
    '- Open questions and follow-up checks: use this section for anything the audit did not fully establish.',
    '',
    'Tone rules:',
    '- Write in plain, direct, operational language.',
    '- Open with the site and findings, not broad industry framing.',
    '- Avoid consultancy-style or theatrical phrasing.',
    '- Keep paragraphs short and remove repeated framing.',
    '',
    'Priority action formatting:',
    '- Each recommendation must include: Issue, Why it matters, Action, Priority, Confidence.',
    '- Allowed Priority values: Immediate, Near-term, Later.',
    '- Allowed Confidence values: High, Medium, Low.',
    '',
    'Ambiguous-signal wording rules:',
    '- For non-binary findings, use: observed signal, bounded implication, verification step.',
    '- Example: The audit saw low-confidence extractability with a 402/403 response. This suggests an access or delivery issue may be interfering with machine retrieval. This should be verified by checking bot rules, CDN behavior, and origin logs before treating it as a confirmed crawler block.',
    '',
    'Output requirements:',
    '- Preserve the site-specific findings that are actually supported.',
    '- Make the report shorter, clearer, and more trustworthy than the source.',
    '- If the source report contains unsupported or overconfident claims, remove or soften them.',
    '- If a recommendation is too vague, rewrite it into a concrete action.',
    '- Do not mention these instructions in the output.',
    '',
    'Report to rewrite:',
    '',
    reportMarkdown,
    '',
  ].join('\n');
}
