/**
 * Fix Pack generators (spec C10) — the "be the fix layer" seam.
 *
 * Every artifact is generated from the same agent registry the scanner grades with,
 * so the fix can never drift from the diagnosis. Artifacts are plain text the owner
 * (or whoever they forward it to) can paste without understanding any of it.
 */
import {
  AGENT_REGISTRY_VERSION,
  agentsByFamily,
} from '../../workers/scan-engine/agent-registry';

export type TrainingChoice = 'allow' | 'block';

/**
 * A ready-to-use robots.txt: retrieval + search agents explicitly allowed, and the
 * training crawlers handled per the owner's business choice — with the reasoning
 * written into the file as comments so the next person to open it understands it.
 */
export function buildRobotsTxt(input: {
  domain: string;
  trainingChoice: TrainingChoice;
  sitemapPath?: string;
}): string {
  const retrieval = agentsByFamily('retrieval');
  const fetchers = agentsByFamily('user_fetcher');
  const conventional = agentsByFamily('conventional_search');
  const training = agentsByFamily('training');
  const lines: string[] = [];

  lines.push(`# robots.txt for ${input.domain}`);
  lines.push(`# Generated by GEO-Pulse (agent registry ${AGENT_REGISTRY_VERSION})`);
  lines.push('#');
  lines.push('# Layout:');
  lines.push('#   1. AI search agents — these decide whether AI engines can cite you. Allowed.');
  lines.push('#   2. User-triggered fetchers — fetch a page when a real person asks an AI about it. Allowed.');
  lines.push('#   3. Classic search engines - Google/Bing. Allowed.');
  lines.push(`#   4. AI TRAINING crawlers — a business choice, not a visibility lever. Currently: ${input.trainingChoice === 'block' ? 'BLOCKED (opted out of model training)' : 'ALLOWED'}.`);
  lines.push('');

  lines.push('# --- 1. AI search agents (control citation in AI answers) ---');
  for (const a of retrieval) {
    lines.push(`User-agent: ${a.token}`);
    lines.push('Allow: /');
    lines.push('');
  }

  lines.push('# --- 2. User-triggered fetchers (serve a live request a person made) ---');
  for (const a of fetchers) {
    lines.push(`User-agent: ${a.token}`);
    lines.push('Allow: /');
    lines.push('');
  }

  lines.push('# --- 3. Classic search engines (Google Search, AI Overviews, Bing/Copilot) ---');
  for (const a of conventional) {
    lines.push(`User-agent: ${a.token}`);
    lines.push('Allow: /');
    lines.push('');
  }

  lines.push('# --- 4. AI training crawlers ---');
  lines.push('# Blocking these opts your content out of model TRAINING. It does NOT affect');
  lines.push('# whether AI search engines can find or cite you — that is section 1 above.');
  lines.push('# Change this section freely; it is a business/IP decision, not an SEO one.');
  for (const a of training) {
    if (!a.respectsRobotsTxt) {
      lines.push(`# ${a.token} ignores robots.txt — only a firewall rule actually stops it.`);
      continue;
    }
    lines.push(`User-agent: ${a.token}`);
    lines.push(input.trainingChoice === 'block' ? 'Disallow: /' : 'Allow: /');
    lines.push('');
  }

  lines.push('# --- Everyone else ---');
  lines.push('User-agent: *');
  lines.push('Allow: /');
  lines.push('Disallow: /wp-admin/');
  lines.push('Allow: /wp-admin/admin-ajax.php');
  lines.push('');
  lines.push(`Sitemap: https://${input.domain}${input.sitemapPath ?? '/sitemap.xml'}`);
  lines.push('');
  return lines.join('\n');
}

/**
 * Cloudflare WAF safelist — a custom-rule expression that stops bot protection from
 * silently eating the compliant AI crawlers robots.txt just allowed.
 */
export function buildCloudflareBotSafelist(): { title: string; steps: string[]; expression: string; note: string } {
  const tokens = [
    ...agentsByFamily('retrieval'),
    ...agentsByFamily('user_fetcher'),
    ...agentsByFamily('conventional_search'),
  ].map((a) => a.token);

  const uaClauses = tokens.map((t) => `(http.user_agent contains "${t}")`).join(' or ');

  return {
    title: 'Cloudflare: let verified AI crawlers through the firewall',
    steps: [
      'Cloudflare dashboard → your site → Security → WAF → Custom rules → Create rule.',
      'Name it "Allow AI search crawlers".',
      'Choose Edit expression and paste the expression below.',
      'Set the action to Skip → select "All remaining custom rules" and the bot-protection features you use (Bot Fight Mode cannot skip — replace it with Super Bot Fight Mode or a custom rule).',
      'Save, then re-run the GEO-Pulse scan to confirm the block is gone.',
    ],
    expression: `(cf.client.bot) or ${uaClauses}`,
    note:
      'cf.client.bot matches Cloudflare-verified good bots (Google, Bing, and verified AI crawlers); the user-agent clauses catch agents not yet on the verified list. User-agent strings can be spoofed — this rule only skips bot checks, it does not grant anything else.',
  };
}

/** Cloudflare Transform Rule for the hygiene response headers. */
export function buildCloudflareSecurityHeaders(): { title: string; steps: string[]; headers: { name: string; value: string }[]; note: string } {
  return {
    title: 'Cloudflare: add the security response headers',
    steps: [
      'Cloudflare dashboard → your site → Rules → Transform Rules → Modify Response Header → Create rule.',
      'Name it "Security headers"; set When incoming requests match → All incoming requests.',
      'Add a "Set static" entry for each header below.',
      'For Strict-Transport-Security you can instead use SSL/TLS → Edge Certificates → Enable HSTS.',
      'Deploy, then check securityheaders.com for your domain.',
    ],
    headers: [
      { name: 'Strict-Transport-Security', value: 'max-age=31536000; includeSubDomains' },
      { name: 'X-Content-Type-Options', value: 'nosniff' },
      { name: 'X-Frame-Options', value: 'SAMEORIGIN' },
    ],
    note: 'Good practice for browsers and security scanners. This is website hygiene — it does not change AI visibility.',
  };
}
