export type IntelligenceSourceCategory =
  | 'audit'
  | 'benchmark'
  | 'evaluation'
  | 'intervention'
  | 'delivery'
  | 'configuration'
  | 'artifact'
  | 'operations';

export type IntelligenceSourceAuthority =
  | 'raw_fact'
  | 'derived_fact'
  | 'generated_narrative'
  | 'configuration'
  | 'operational_log';

export type IntelligenceSourceAccess =
  | 'service_role'
  | 'tenant_rls'
  | 'platform_admin'
  | 'public_capability'
  | 'runtime_binding';

export type IntelligenceSourceDefinition = {
  readonly id: string;
  readonly category: IntelligenceSourceCategory;
  readonly authority: IntelligenceSourceAuthority;
  readonly storage: 'postgres' | 'r2' | 'worker_log';
  readonly schema?: 'public' | 'analytics';
  readonly table?: string;
  readonly artifactKind?: string;
  readonly producers: readonly string[];
  readonly consumers: readonly string[];
  readonly identityFields: readonly string[];
  readonly timestampFields: readonly string[];
  readonly statusFields: readonly string[];
  readonly versionFields: readonly string[];
  readonly access: IntelligenceSourceAccess;
  readonly retention: 'product_record' | 'measurement_history' | 'operational' | 'generated_artifact';
  readonly knownFailureModes: readonly string[];
};

export type PostgresIntelligenceSource = IntelligenceSourceDefinition & {
  readonly storage: 'postgres';
  readonly schema: 'public' | 'analytics';
  readonly table: string;
};

const source = (
  definition: IntelligenceSourceDefinition
): IntelligenceSourceDefinition => definition;

/**
 * Product-wide registry for data that participates in measurement, evidence,
 * evaluation, recommendations, implementation, or delivery lineage.
 *
 * This is deliberately metadata only. Operational tables remain authoritative;
 * later intelligence-plane issues may index them but must not silently replace them.
 */
export const INTELLIGENCE_SOURCE_REGISTRY: readonly IntelligenceSourceDefinition[] = [
  source({
    id: 'public.scans',
    category: 'audit',
    authority: 'raw_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'scans',
    producers: ['app/api/scan/route.ts', 'lib/server/recurring-audits.ts', 'lib/server/competitor-cohorts.ts'],
    consumers: ['results API/UI', 'dashboards', 'fix agent', 'report queue', 'score benchmark'],
    identityFields: ['id', 'domain', 'url', 'user_id', 'agency_account_id', 'agency_client_id', 'startup_workspace_id'],
    timestampFields: ['created_at'],
    statusFields: ['status', 'run_source'],
    versionFields: ['effective_model', 'full_results_json.checkCatalogVersion'],
    access: 'tenant_rls',
    retention: 'measurement_history',
    knownFailureModes: ['duplicate domain scans', 'mixed run sources', 'missing vertical snapshots', 'legacy rows without catalog version'],
  }),
  source({
    id: 'public.scan_runs',
    category: 'audit',
    authority: 'raw_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'scan_runs',
    producers: ['Stripe/deep-audit queue setup', 'workers/scan-engine/deep-audit-crawl.ts'],
    consumers: ['report queue', 'scan progress', 'report status'],
    identityFields: ['id', 'scan_id', 'domain'],
    timestampFields: ['created_at', 'started_at', 'completed_at'],
    statusFields: ['config.crawl_pending'],
    versionFields: ['version', 'config.model_policy'],
    access: 'tenant_rls',
    retention: 'measurement_history',
    knownFailureModes: ['orphaned in-progress work', 'partial continuation state', 'one-row-per-scan legacy constraint'],
  }),
  source({
    id: 'public.scan_pages',
    category: 'audit',
    authority: 'raw_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'scan_pages',
    producers: ['workers/scan-engine/deep-audit-crawl.ts'],
    consumers: ['deep report builder', 'scan progress', 'coverage computation'],
    identityFields: ['id', 'run_id', 'url', 'normalized_url', 'canonical_url', 'parent_id'],
    timestampFields: ['created_at'],
    statusFields: ['status', 'http_status', 'blocked_by_robots'],
    versionFields: ['issues_json.checkCatalogVersion'],
    access: 'tenant_rls',
    retention: 'measurement_history',
    knownFailureModes: ['partial crawl', 'redirect identity drift', 'missing page-level catalog version'],
  }),
  source({
    id: 'public.reports',
    category: 'delivery',
    authority: 'generated_narrative',
    storage: 'postgres',
    schema: 'public',
    table: 'reports',
    producers: ['workers/queue/report-queue-consumer.ts'],
    consumers: ['results/report UI', 'email delivery', 'dashboard'],
    identityFields: ['id', 'scan_id', 'user_id', 'agency_account_id', 'agency_client_id'],
    timestampFields: ['created_at', 'pdf_generated_at', 'email_delivered_at'],
    statusFields: ['type'],
    versionFields: [],
    access: 'tenant_rls',
    retention: 'product_record',
    knownFailureModes: ['artifact URL without recoverable version', 'delivery completed after source job failure'],
  }),
  source({
    id: 'r2.audit_artifacts',
    category: 'artifact',
    authority: 'generated_narrative',
    storage: 'r2',
    artifactKind: 'markdown/pdf audit reports and branding assets',
    producers: ['workers/report/r2-report-storage.ts', 'workers/queue/report-queue-consumer.ts'],
    consumers: ['report proxy', 'email delivery', 'report viewer'],
    identityFields: ['R2 object key', 'scan/report id embedded by producer'],
    timestampFields: [],
    statusFields: [],
    versionFields: ['object metadata when present'],
    access: 'runtime_binding',
    retention: 'generated_artifact',
    knownFailureModes: ['missing metadata', 'database row points to absent object', 'public URL used as identity'],
  }),
  source({
    id: 'public.benchmark_domains',
    category: 'benchmark',
    authority: 'configuration',
    storage: 'postgres',
    schema: 'public',
    table: 'benchmark_domains',
    producers: ['benchmark seed/import scripts', 'admin benchmark tools', 'competitor cohort tools'],
    consumers: ['benchmark scheduler', 'runner', 'cohorts', 'client outcome engine'],
    identityFields: ['id', 'canonical_domain', 'site_url'],
    timestampFields: ['created_at', 'updated_at'],
    statusFields: ['metadata.schedule_enabled', 'metadata.seed_priority'],
    versionFields: ['metadata.schedule_query_set_id'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['mixed identity and schedule configuration', 'aliases held only in metadata', 'vertical drift'],
  }),
  source({
    id: 'public.benchmark_query_sets',
    category: 'benchmark',
    authority: 'configuration',
    storage: 'postgres',
    schema: 'public',
    table: 'benchmark_query_sets',
    producers: ['benchmark query-set seed scripts'],
    consumers: ['benchmark scheduler', 'runner', 'cohort frames'],
    identityFields: ['id', 'name', 'version', 'vertical'],
    timestampFields: ['created_at'],
    statusFields: ['status'],
    versionFields: ['version'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['status does not prove scheduling', 'semantically changed fixture under reused version'],
  }),
  source({
    id: 'public.benchmark_queries',
    category: 'benchmark',
    authority: 'configuration',
    storage: 'postgres',
    schema: 'public',
    table: 'benchmark_queries',
    producers: ['benchmark query-set seed scripts', 'tracked prompt actions'],
    consumers: ['benchmark runner', 'client outcome engine', 'admin drilldown'],
    identityFields: ['id', 'query_set_id', 'query_key'],
    timestampFields: ['created_at'],
    statusFields: ['intent_type'],
    versionFields: ['query_set_id'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['query text changed without new query-set version', 'mixed-fit query/domain combinations'],
  }),
  source({
    id: 'public.benchmark_run_groups',
    category: 'benchmark',
    authority: 'raw_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'benchmark_run_groups',
    producers: ['lib/server/benchmark-runner.ts', 'lib/server/benchmark-schedule.ts'],
    consumers: ['admin benchmark views', 'schedule health', 'daily recap', 'cohort comparisons'],
    identityFields: ['id', 'query_set_id', 'metadata.domain_id', 'metadata.schedule_run_key'],
    timestampFields: ['created_at', 'started_at', 'completed_at'],
    statusFields: ['status', 'run_scope'],
    versionFields: ['model_set_version', 'metadata.schedule_version', 'metadata.run_mode'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['stale running rows', 'parent completed/failed inconsistent with child runs', 'partial cron window'],
  }),
  source({
    id: 'public.query_runs',
    category: 'benchmark',
    authority: 'raw_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'query_runs',
    producers: ['lib/server/benchmark-runner.ts'],
    consumers: ['citation parser lineage', 'metrics', 'admin drilldown', 'client outcome engine'],
    identityFields: ['id', 'run_group_id', 'domain_id', 'query_id'],
    timestampFields: ['created_at', 'executed_at'],
    statusFields: ['status', 'error_message'],
    versionFields: ['model_id', 'auditor_model_id', 'response_metadata.provider'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['provider failure represented beside genuine empty result', 'raw response missing', 'runtime metadata shape drift'],
  }),
  source({
    id: 'public.query_citations',
    category: 'benchmark',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'query_citations',
    producers: ['lib/server/benchmark-runner.ts citation parser'],
    consumers: ['benchmark metrics', 'citation evidence', 'client outcome engine', 'portfolio and recap views'],
    identityFields: ['id', 'query_run_id', 'cited_domain', 'cited_url', 'grounding_evidence_id'],
    timestampFields: ['created_at'],
    statusFields: ['citation_type', 'sentiment'],
    versionFields: ['metadata parser/provenance fields'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['parser version not first-class', 'brand mention ambiguity', 'domain-level attribution without exact page'],
  }),
  source({
    id: 'public.benchmark_domain_metrics',
    category: 'benchmark',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'benchmark_domain_metrics',
    producers: ['lib/server/benchmark-runner.ts'],
    consumers: ['dashboards', 'visibility reports', 'client outcome engine', 'cohort views'],
    identityFields: ['id', 'run_group_id', 'domain_id', 'model_id'],
    timestampFields: ['created_at', 'computed_at'],
    statusFields: [],
    versionFields: ['metrics.run_mode', 'metrics execution metadata'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['zero conflated with unavailable', 'metric definition version not first-class', 'derived from partial window'],
  }),
  source({
    id: 'public.benchmark_cohorts',
    category: 'benchmark',
    authority: 'configuration',
    storage: 'postgres',
    schema: 'public',
    table: 'benchmark_cohorts',
    producers: ['cohort seed/admin tools'],
    consumers: ['benchmark domain history comparison'],
    identityFields: ['id', 'name', 'query_set_id', 'vertical'],
    timestampFields: ['created_at'],
    statusFields: ['status', 'run_mode'],
    versionFields: ['model_id', 'benchmark_window_label'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['compatibility dimensions incomplete', 'membership changes without explicit cohort version'],
  }),
  source({
    id: 'public.benchmark_cohort_members',
    category: 'benchmark',
    authority: 'configuration',
    storage: 'postgres',
    schema: 'public',
    table: 'benchmark_cohort_members',
    producers: ['cohort seed/admin tools'],
    consumers: ['cohort comparison'],
    identityFields: ['id', 'cohort_id', 'domain_id'],
    timestampFields: ['created_at'],
    statusFields: ['role'],
    versionFields: ['cohort_id'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['membership history not temporal'],
  }),
  source({
    id: 'public.client_benchmark_configs',
    category: 'configuration',
    authority: 'configuration',
    storage: 'postgres',
    schema: 'public',
    table: 'client_benchmark_configs',
    producers: ['tracked prompt/config actions'],
    consumers: ['benchmark scheduling', 'client outcome actions'],
    identityFields: ['id', 'agency_account_id', 'startup_workspace_id', 'benchmark_domain_id', 'query_set_id'],
    timestampFields: ['created_at', 'updated_at'],
    statusFields: ['cadence'],
    versionFields: ['metadata'],
    access: 'tenant_rls',
    retention: 'product_record',
    knownFailureModes: ['domain config diverges from benchmark-domain metadata', 'action events stored in metadata'],
  }),
  source({
    id: 'public.report_eval_runs',
    category: 'evaluation',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'report_eval_runs',
    producers: ['scripts/report-eval-smoke.ts', 'scripts/promptfoo-eval-write.ts', 'lib/server/report-eval-writer.ts'],
    consumers: ['admin eval dashboard'],
    identityFields: ['id', 'domain', 'site_url'],
    timestampFields: ['created_at'],
    statusFields: [],
    versionFields: ['framework', 'rubric_version', 'prompt_set_name', 'metadata'],
    access: 'platform_admin',
    retention: 'measurement_history',
    knownFailureModes: ['offline fixture mixed with production artifact', 'source report/run lineage optional'],
  }),
  source({
    id: 'public.retrieval_eval_runs',
    category: 'evaluation',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'retrieval_eval_runs',
    producers: ['scripts/retrieval-eval-write.ts', 'scripts/promptfoo-eval-write.ts'],
    consumers: ['admin eval dashboard and drilldown'],
    identityFields: ['id', 'domain', 'site_url'],
    timestampFields: ['created_at'],
    statusFields: [],
    versionFields: ['framework', 'dataset_version', 'retriever_version', 'generator_version', 'metadata'],
    access: 'platform_admin',
    retention: 'measurement_history',
    knownFailureModes: ['synthetic and live passages not distinguished consistently', 'domain identity is text-only'],
  }),
  source({
    id: 'public.retrieval_eval_prompts',
    category: 'evaluation',
    authority: 'raw_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'retrieval_eval_prompts',
    producers: ['retrieval eval writers'],
    consumers: ['retrieval drilldown'],
    identityFields: ['id', 'run_id', 'prompt_key'],
    timestampFields: ['created_at'],
    statusFields: [],
    versionFields: ['run_id'],
    access: 'platform_admin',
    retention: 'measurement_history',
    knownFailureModes: ['prompt identity scoped only to run'],
  }),
  source({
    id: 'public.retrieval_eval_passages',
    category: 'evaluation',
    authority: 'raw_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'retrieval_eval_passages',
    producers: ['retrieval eval writers'],
    consumers: ['retrieval drilldown'],
    identityFields: ['id', 'run_id', 'prompt_id', 'scan_page_url', 'source_url'],
    timestampFields: ['created_at'],
    statusFields: ['rank'],
    versionFields: ['run_id'],
    access: 'platform_admin',
    retention: 'measurement_history',
    knownFailureModes: ['passage content has no shared evidence ID', 'source URL normalization drift'],
  }),
  source({
    id: 'public.retrieval_eval_answers',
    category: 'evaluation',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'retrieval_eval_answers',
    producers: ['retrieval eval writers'],
    consumers: ['retrieval drilldown'],
    identityFields: ['id', 'run_id', 'prompt_id'],
    timestampFields: ['created_at'],
    statusFields: [],
    versionFields: ['run_id', 'metrics'],
    access: 'platform_admin',
    retention: 'measurement_history',
    knownFailureModes: ['metric definitions embedded in JSON', 'answer lacks common artifact lineage'],
  }),
  source({
    id: 'public.startup_recommendations',
    category: 'intervention',
    authority: 'generated_narrative',
    storage: 'postgres',
    schema: 'public',
    table: 'startup_recommendations',
    producers: ['startup audit/report ingestion', 'manual/admin actions', 'startup agents'],
    consumers: ['startup dashboard', 'implementation plan', 'PR workflow', 'client outcome reporting'],
    identityFields: ['id', 'startup_workspace_id', 'scan_id', 'report_id', 'source_ref'],
    timestampFields: ['created_at', 'updated_at', 'status_changed_at'],
    statusFields: ['status', 'priority', 'confidence'],
    versionFields: ['source_kind', 'metadata'],
    access: 'tenant_rls',
    retention: 'product_record',
    knownFailureModes: ['recommendation duplicates across reports', 'evidence JSON lacks canonical evidence IDs'],
  }),
  source({
    id: 'public.startup_recommendation_status_events',
    category: 'intervention',
    authority: 'raw_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'startup_recommendation_status_events',
    producers: ['startup recommendation lifecycle service', 'PR workflow'],
    consumers: ['startup timeline', 'outcome tracking'],
    identityFields: ['id', 'recommendation_id', 'startup_workspace_id'],
    timestampFields: ['created_at'],
    statusFields: ['from_status', 'to_status'],
    versionFields: ['metadata'],
    access: 'tenant_rls',
    retention: 'product_record',
    knownFailureModes: ['manual status can be mistaken for measured verification'],
  }),
  source({
    id: 'public.startup_implementation_plans',
    category: 'intervention',
    authority: 'generated_narrative',
    storage: 'postgres',
    schema: 'public',
    table: 'startup_implementation_plans',
    producers: ['startup audit planning workflow'],
    consumers: ['startup dashboard', 'execution dispatch'],
    identityFields: ['id', 'startup_workspace_id', 'scan_id', 'report_id'],
    timestampFields: ['created_at', 'updated_at'],
    statusFields: ['status'],
    versionFields: ['metadata'],
    access: 'tenant_rls',
    retention: 'product_record',
    knownFailureModes: ['plan regenerated without stable relationship to prior plan'],
  }),
  source({
    id: 'public.startup_implementation_plan_tasks',
    category: 'intervention',
    authority: 'generated_narrative',
    storage: 'postgres',
    schema: 'public',
    table: 'startup_implementation_plan_tasks',
    producers: ['startup audit planning workflow'],
    consumers: ['execution dispatch', 'PR workflow', 'startup dashboard'],
    identityFields: ['id', 'plan_id', 'recommendation_id'],
    timestampFields: ['created_at', 'updated_at'],
    statusFields: ['status', 'execution_mode', 'task_kind', 'agent_role'],
    versionFields: ['metadata'],
    access: 'tenant_rls',
    retention: 'product_record',
    knownFailureModes: ['execution completion does not itself prove site outcome'],
  }),
  source({
    id: 'public.startup_agent_pr_runs',
    category: 'intervention',
    authority: 'raw_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'startup_agent_pr_runs',
    producers: ['startup agent PR workflow'],
    consumers: ['startup dashboard', 'recommendation lifecycle'],
    identityFields: ['id', 'startup_workspace_id', 'recommendation_id'],
    timestampFields: ['created_at', 'completed_at'],
    statusFields: ['status', 'error_message'],
    versionFields: ['metadata'],
    access: 'tenant_rls',
    retention: 'product_record',
    knownFailureModes: ['PR opened/merged status can be stale', 'multiple tasks grouped into one run'],
  }),
  source({
    id: 'public.startup_agent_pr_run_events',
    category: 'intervention',
    authority: 'raw_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'startup_agent_pr_run_events',
    producers: ['startup agent PR workflow'],
    consumers: ['startup timeline', 'execution audit'],
    identityFields: ['id', 'run_id', 'startup_workspace_id', 'recommendation_id'],
    timestampFields: ['created_at'],
    statusFields: ['from_status', 'to_status'],
    versionFields: ['metadata'],
    access: 'tenant_rls',
    retention: 'product_record',
    knownFailureModes: ['external GitHub state can drift from recorded event'],
  }),
  source({
    id: 'public.startup_audit_executions',
    category: 'intervention',
    authority: 'raw_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'startup_audit_executions',
    producers: ['startup audit orchestration'],
    consumers: ['startup planning/execution UI', 'dispatch scheduler'],
    identityFields: ['id', 'startup_workspace_id', 'scan_id', 'report_id'],
    timestampFields: ['created_at', 'started_at', 'completed_at'],
    statusFields: ['status'],
    versionFields: ['model_policy', 'metadata'],
    access: 'tenant_rls',
    retention: 'product_record',
    knownFailureModes: ['partial multi-role orchestration', 'model response contract failure'],
  }),
  source({
    id: 'public.startup_audit_execution_events',
    category: 'intervention',
    authority: 'raw_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'startup_audit_execution_events',
    producers: ['startup audit orchestration'],
    consumers: ['startup timeline', 'admin diagnostics'],
    identityFields: ['id', 'execution_id', 'startup_workspace_id'],
    timestampFields: ['created_at'],
    statusFields: ['from_status', 'to_status'],
    versionFields: ['metadata'],
    access: 'tenant_rls',
    retention: 'product_record',
    knownFailureModes: ['event completeness depends on orchestration failure handling'],
  }),
  source({
    id: 'public.recurring_audit_schedules',
    category: 'configuration',
    authority: 'configuration',
    storage: 'postgres',
    schema: 'public',
    table: 'recurring_audit_schedules',
    producers: ['recurring audit settings/actions'],
    consumers: ['hourly Worker cron', 'dashboard'],
    identityFields: ['id', 'user_id', 'startup_workspace_id', 'url'],
    timestampFields: ['created_at', 'updated_at', 'next_run_at', 'last_run_at'],
    statusFields: ['enabled', 'cadence'],
    versionFields: [],
    access: 'tenant_rls',
    retention: 'product_record',
    knownFailureModes: ['schedule advanced before downstream tail completes', 'domain identity text drift'],
  }),
  source({
    id: 'public.monitoring_subscriptions',
    category: 'configuration',
    authority: 'configuration',
    storage: 'postgres',
    schema: 'public',
    table: 'monitoring_subscriptions',
    producers: ['monitor checkout/webhooks'],
    consumers: ['monitor cron', 'delivery UI'],
    identityFields: ['id', 'email', 'domain', 'origin_scan_id', 'private_token'],
    timestampFields: ['created_at', 'updated_at', 'next_audit_at', 'last_audit_at'],
    statusFields: ['status', 'plan'],
    versionFields: [],
    access: 'service_role',
    retention: 'product_record',
    knownFailureModes: ['email-keyed identity', 'subscription active while audit scheduling is stale'],
  }),
  source({
    id: 'public.gpm_reports',
    category: 'delivery',
    authority: 'generated_narrative',
    storage: 'postgres',
    schema: 'public',
    table: 'gpm_reports',
    producers: ['geo-performance schedule/report workflow'],
    consumers: ['GPM email delivery', 'admin/client reporting'],
    identityFields: ['id', 'config_id', 'run_group_id', 'startup_workspace_id', 'agency_account_id'],
    timestampFields: ['created_at', 'generated_at'],
    statusFields: ['platform', 'narrative_generated'],
    versionFields: ['report_payload_version', 'metadata'],
    access: 'tenant_rls',
    retention: 'product_record',
    knownFailureModes: ['generated narrative can outlive corrected source metrics'],
  }),
  source({
    id: 'public.self_improvement_runs',
    category: 'evaluation',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'self_improvement_runs',
    producers: ['lib/server/self-improvement.ts'],
    consumers: ['admin automation UI', 'external coding-agent workflow'],
    identityFields: ['id', 'target_url'],
    timestampFields: ['created_at'],
    statusFields: ['status', 'trigger_source'],
    versionFields: ['summary'],
    access: 'platform_admin',
    retention: 'measurement_history',
    knownFailureModes: ['summary-only evidence', 'external ship step not part of same transaction'],
  }),
  source({
    id: 'public.service_model_policies',
    category: 'configuration',
    authority: 'configuration',
    storage: 'postgres',
    schema: 'public',
    table: 'service_model_policies',
    producers: ['admin service controls'],
    consumers: ['scan, benchmark, and agent model routing'],
    identityFields: ['id', 'service_id', 'scope_type', 'bundle_id', 'agency_account_id', 'agency_client_id'],
    timestampFields: ['created_at', 'updated_at'],
    statusFields: ['is_active'],
    versionFields: ['provider_name', 'model_id', 'fallback_provider_name', 'fallback_model_id'],
    access: 'platform_admin',
    retention: 'product_record',
    knownFailureModes: ['effective runtime policy not snapshotted by every producer'],
  }),
  source({
    id: 'public.intelligence_domains',
    category: 'configuration',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_domains',
    producers: ['scripts/intelligence-identity-backfill.ts', 'canonical identity repository'],
    consumers: ['intelligence run/evidence indexes', 'admin intelligence control room'],
    identityFields: ['id', 'normalized_host'],
    timestampFields: ['created_at', 'updated_at'],
    statusFields: ['review_state'],
    versionFields: ['normalization_version'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['normalization collision', 'unreviewed rebrand', 'subdomain policy mismatch'],
  }),
  source({
    id: 'public.intelligence_domain_aliases',
    category: 'configuration',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_domain_aliases',
    producers: ['scripts/intelligence-identity-backfill.ts', 'canonical identity repository'],
    consumers: ['canonical host resolver', 'identity review tooling'],
    identityFields: ['id', 'domain_id', 'alias_host'],
    timestampFields: ['created_at', 'updated_at'],
    statusFields: ['relationship', 'review_state'],
    versionFields: ['normalization_version'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['alias associated with multiple domains', 'redirect treated as verified before review'],
  }),
  source({
    id: 'public.intelligence_domain_owners',
    category: 'configuration',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_domain_owners',
    producers: ['scripts/intelligence-identity-backfill.ts'],
    consumers: ['tenant-scoped intelligence projections'],
    identityFields: ['id', 'domain_id', 'owner_type', 'owner_id'],
    timestampFields: ['created_at', 'updated_at'],
    statusFields: ['visibility'],
    versionFields: [],
    access: 'service_role',
    retention: 'product_record',
    knownFailureModes: ['missing ownership link', 'same host observed by multiple tenants'],
  }),
  source({
    id: 'public.intelligence_pages',
    category: 'configuration',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_pages',
    producers: ['scripts/intelligence-identity-backfill.ts'],
    consumers: ['evidence catalog', 'retrieval and page history'],
    identityFields: ['id', 'domain_id', 'normalized_url', 'original_url'],
    timestampFields: ['created_at', 'updated_at'],
    statusFields: [],
    versionFields: ['normalization_version'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['query parameter semantics collapsed incorrectly', 'redirect changes page host'],
  }),
  source({
    id: 'public.intelligence_source_identity_maps',
    category: 'configuration',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_source_identity_maps',
    producers: ['scripts/intelligence-identity-backfill.ts'],
    consumers: ['canonical identity repository', 'run and evidence index backfills'],
    identityFields: ['id', 'source_kind', 'source_id', 'canonical_domain_id', 'canonical_page_id'],
    timestampFields: ['created_at', 'updated_at'],
    statusFields: ['mapping_status', 'unmapped_reason'],
    versionFields: ['normalization_version'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['source added without adapter', 'mapping version drift', 'source deletion leaves historical pointer'],
  }),
  source({
    id: 'public.intelligence_measurement_lanes',
    category: 'configuration',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_measurement_lanes',
    producers: ['scripts/intelligence-measurement-lane-backfill.ts', 'future versioned run producers'],
    consumers: ['compatibility evaluator', 'run index', 'analytical marts'],
    identityFields: ['id', 'fingerprint'],
    timestampFields: ['created_at', 'updated_at'],
    statusFields: ['frame_kind', 'review_state'],
    versionFields: ['protocol_version', 'protocol'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['unknown version dimension', 'protocol field omitted by producer'],
  }),
  source({
    id: 'public.intelligence_measurement_windows',
    category: 'benchmark',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_measurement_windows',
    producers: ['scripts/intelligence-measurement-lane-backfill.ts', 'future scheduled run producers'],
    consumers: ['quality gates', 'coverage monitoring', 'comparison marts'],
    identityFields: ['id', 'lane_id', 'window_key', 'source_schedule_key'],
    timestampFields: ['created_at', 'scheduled_for', 'started_at', 'completed_at'],
    statusFields: ['quality_state'],
    versionFields: ['lane_id'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['expected coverage unknown', 'partial window mistaken for complete'],
  }),
  source({
    id: 'public.intelligence_measurement_run_mappings',
    category: 'benchmark',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_measurement_run_mappings',
    producers: ['scripts/intelligence-measurement-lane-backfill.ts'],
    consumers: ['canonical run index', 'compatibility queries'],
    identityFields: ['id', 'source_kind', 'source_id', 'lane_id', 'window_id'],
    timestampFields: ['created_at', 'updated_at'],
    statusFields: ['mapping_status', 'mapping_reason'],
    versionFields: ['lane_id'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['legacy run lacks protocol version', 'source adapter missing'],
  }),
  source({
    id: 'public.intelligence_runs',
    category: 'operations',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_runs',
    producers: ['scripts/intelligence-run-index-backfill.ts', 'future run adapters'],
    consumers: ['evidence catalog', 'quality gates', 'control room', 'reasoning API'],
    identityFields: ['id', 'source_kind', 'source_id', 'canonical_domain_id', 'canonical_page_id', 'parent_run_id'],
    timestampFields: ['indexed_at', 'started_at', 'completed_at', 'observed_at'],
    statusFields: ['source_status', 'quality_state', 'visibility'],
    versionFields: ['contract_version', 'versions', 'lane_id'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['source adapter missing', 'orphaned parent', 'source snapshot drift'],
  }),
  source({
    id: 'public.intelligence_backfill_checkpoints',
    category: 'operations',
    authority: 'operational_log',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_backfill_checkpoints',
    producers: ['intelligence backfill scripts'],
    consumers: ['operators', 'admin intelligence control room'],
    identityFields: ['id', 'backfill_key', 'last_source_key'],
    timestampFields: ['started_at', 'completed_at', 'updated_at'],
    statusFields: ['status'],
    versionFields: ['contract_version', 'source_snapshot'],
    access: 'service_role',
    retention: 'operational',
    knownFailureModes: ['interrupted batch', 'snapshot mismatch', 'stale checkpoint'],
  }),
  source({
    id: 'public.app_logs',
    category: 'operations',
    authority: 'operational_log',
    storage: 'postgres',
    schema: 'public',
    table: 'app_logs',
    producers: ['structured application and Worker logging'],
    consumers: ['admin logs', 'operator diagnostics'],
    identityFields: ['id'],
    timestampFields: ['created_at'],
    statusFields: ['level', 'event'],
    versionFields: ['metadata'],
    access: 'platform_admin',
    retention: 'operational',
    knownFailureModes: ['best-effort inserts can be lossy', 'metadata shape varies by event'],
  }),
  source({
    id: 'worker.scan_report_queue',
    category: 'operations',
    authority: 'operational_log',
    storage: 'worker_log',
    artifactKind: 'Cloudflare Queue messages for deep-audit crawl, report generation, and guarded DLQ replay',
    producers: ['checkout/webhook/reconciliation routes', 'deep-audit continuation'],
    consumers: ['workers/queue/report-queue-consumer.ts', 'workers/queue/dlq-replay.ts'],
    identityFields: ['paymentId', 'scanId', 'queue message id', 'report:dlq-replay KV key'],
    timestampFields: ['queue enqueue/attempt timestamps'],
    statusFields: ['ack', 'retry', 'DLQ', 'guarded replay'],
    versionFields: ['ReportQueueMessage version'],
    access: 'runtime_binding',
    retention: 'operational',
    knownFailureModes: ['retry exhaustion', 'invalid payload', 'missing queue/KV binding', 'DLQ replay suppressed or failed'],
  }),
  source({
    id: 'worker.distribution_queue',
    category: 'operations',
    authority: 'operational_log',
    storage: 'worker_log',
    artifactKind: 'Cloudflare Queue and DLQ messages for scheduled content delivery',
    producers: ['lib/server/distribution-job-schedule.ts'],
    consumers: ['workers/queue/distribution-job-queue-consumer.ts'],
    identityFields: ['distribution job id', 'queue message id'],
    timestampFields: ['queue enqueue/attempt timestamps'],
    statusFields: ['ack', 'retry', 'DLQ'],
    versionFields: ['DistributionQueueMessage version'],
    access: 'runtime_binding',
    retention: 'operational',
    knownFailureModes: ['retry exhaustion', 'invalid payload', 'database job missing', 'DLQ status reconciliation failure'],
  }),
  source({
    id: 'worker.cron',
    category: 'operations',
    authority: 'operational_log',
    storage: 'worker_log',
    artifactKind: 'hourly scheduled dispatch and structured stage logs',
    producers: ['workers/cloudflare-entry.ts scheduled handler'],
    consumers: ['Cloudflare observability', 'app_logs for selected workflows'],
    identityFields: ['cron invocation timestamp', 'schedule/window keys emitted by child jobs'],
    timestampFields: ['event scheduledTime', 'structured log timestamp'],
    statusFields: ['cron_stage', 'child workflow status'],
    versionFields: ['deployed Worker version', 'wrangler schedule configuration'],
    access: 'runtime_binding',
    retention: 'operational',
    knownFailureModes: ['tail starvation', 'invocation timeout', 'child failure after schedule advancement', 'logs retained outside Postgres'],
  }),
  source({
    id: 'public.intelligence_evidence_objects',
    category: 'artifact',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_evidence_objects',
    producers: ['scripts/intelligence-evidence-backfill.ts', 'future intelligence ingestion adapters'],
    consumers: ['citation resolver', 'recommendation lineage', 'retrieval experiments', 'admin intelligence control room'],
    identityFields: ['stable_evidence_id', 'source_kind', 'source_id', 'evidence_kind'],
    timestampFields: ['source_created_at', 'collected_at', 'indexed_at'],
    statusFields: ['artifact_status', 'privacy'],
    versionFields: ['contract_version', 'parser_version', 'extractor_version'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['source pointer becomes unavailable', 'R2 pointer is unverified', 'tenant ownership absent in legacy source'],
  }),
  source({
    id: 'public.intelligence_evidence_edges',
    category: 'artifact',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_evidence_edges',
    producers: ['scripts/intelligence-evidence-backfill.ts', 'future intelligence ingestion adapters'],
    consumers: ['citation resolver', 'recommendation lineage', 'retrieval experiments'],
    identityFields: ['from_evidence_id', 'to_evidence_id', 'relation'],
    timestampFields: ['created_at'],
    statusFields: ['relation'],
    versionFields: [],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['parent evidence not indexed yet', 'derived evidence points only to an aggregate'],
  }),
  source({
    id: 'public.intelligence_quality_policies',
    category: 'configuration',
    authority: 'configuration',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_quality_policies',
    producers: ['versioned database migrations'],
    consumers: ['scripts/intelligence-quality-classify.ts', 'analytical eligibility gates', 'admin intelligence control room'],
    identityFields: ['policy_version'],
    timestampFields: ['created_at', 'retired_at'],
    statusFields: ['is_active'],
    versionFields: ['policy_version'],
    access: 'service_role',
    retention: 'product_record',
    knownFailureModes: ['multiple active versions', 'classification runner uses an unavailable policy'],
  }),
  source({
    id: 'public.intelligence_run_quality_classifications',
    category: 'operations',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_run_quality_classifications',
    producers: ['scripts/intelligence-quality-classify.ts'],
    consumers: ['analytical eligibility gates', 'admin intelligence control room', 'quality alerts'],
    identityFields: ['stable_classification_id', 'source_kind', 'source_id', 'source_snapshot'],
    timestampFields: ['classified_at'],
    statusFields: ['quality_state'],
    versionFields: ['policy_version'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['source changes after classification', 'missing run-index mapping', 'policy drift'],
  }),
  source({
    id: 'public.intelligence_window_quality_assessments',
    category: 'benchmark',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_window_quality_assessments',
    producers: ['scripts/intelligence-quality-classify.ts'],
    consumers: ['analytical marts', 'admin intelligence control room', 'quality alerts'],
    identityFields: ['policy_version', 'source_kind', 'source_id', 'source_snapshot'],
    timestampFields: ['assessed_at'],
    statusFields: ['eligible', 'anomaly_codes'],
    versionFields: ['policy_version'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['unknown protocol mode', 'missing comparison cell', 'false-positive cohort anomaly'],
  }),
  source({
    id: 'public.intelligence_quarantine_events',
    category: 'operations',
    authority: 'operational_log',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_quarantine_events',
    producers: ['quality policy', 'platform operators'],
    consumers: ['quality classifier', 'admin intelligence control room', 'analytical eligibility gates'],
    identityFields: ['id', 'source_kind', 'source_id'],
    timestampFields: ['created_at'],
    statusFields: ['action', 'reason_code'],
    versionFields: [],
    access: 'platform_admin',
    retention: 'measurement_history',
    knownFailureModes: ['release without matching quarantine', 'missing operator rationale'],
  }),
  source({
    id: 'public.intelligence_quality_alerts',
    category: 'operations',
    authority: 'operational_log',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_quality_alerts',
    producers: ['scripts/intelligence-quality-classify.ts'],
    consumers: ['admin intelligence control room', 'operator notification adapters'],
    identityFields: ['alert_key', 'observed_at'],
    timestampFields: ['observed_at', 'resolved_at', 'created_at'],
    statusFields: ['severity', 'reason_code', 'resolved_at'],
    versionFields: ['policy_version'],
    access: 'platform_admin',
    retention: 'operational',
    knownFailureModes: ['duplicate alert windows', 'alert remains open after source recovery'],
  }),
  source({
    id: 'public.intelligence_metric_definitions',
    category: 'configuration',
    authority: 'configuration',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_metric_definitions',
    producers: ['versioned database migrations'],
    consumers: ['analytical marts', 'metric APIs', 'admin intelligence control room'],
    identityFields: ['metric_key', 'dictionary_version'],
    timestampFields: ['created_at'],
    statusFields: ['status'],
    versionFields: ['dictionary_version'],
    access: 'service_role',
    retention: 'product_record',
    knownFailureModes: ['definition changed without version increment', 'consumer omits compatibility rule'],
  }),
  source({
    id: 'public.intelligence_mart_domain_measurement_timeline',
    category: 'benchmark',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_mart_domain_measurement_timeline',
    producers: ['supabase/migrations/064_intelligence_analytical_marts.sql'],
    consumers: ['trend APIs', 'intervention outcomes', 'admin intelligence control room'],
    identityFields: ['canonical_domain_id', 'observed_at', 'query_id', 'model_id', 'run_mode'],
    timestampFields: ['observed_at'],
    statusFields: ['comparison_label'],
    versionFields: ['metric_dictionary_version'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['consumer aggregates repeat domains without deduplication', 'incompatible lanes compared'],
  }),
  source({
    id: 'public.intelligence_mart_lane_window_health',
    category: 'operations',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_mart_lane_window_health',
    producers: ['supabase/migrations/064_intelligence_analytical_marts.sql'],
    consumers: ['analytical gate diagnostics', 'admin intelligence control room'],
    identityFields: ['source_kind', 'source_id', 'lane_id', 'window_id'],
    timestampFields: ['refreshed_at'],
    statusFields: ['eligible', 'metric_status'],
    versionFields: ['metric_dictionary_version'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['assessment stale after source change', 'synthetic window lacks canonical mapping'],
  }),
  source({
    id: 'public.intelligence_mart_domain_query_model_outcomes',
    category: 'benchmark',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_mart_domain_query_model_outcomes',
    producers: ['supabase/migrations/064_intelligence_analytical_marts.sql'],
    consumers: ['benchmark APIs', 'domain timeline', 'intervention outcomes'],
    identityFields: ['query_run_id', 'canonical_domain_id', 'query_id', 'model_id', 'run_mode'],
    timestampFields: ['observed_at', 'refreshed_at'],
    statusFields: ['eligible', 'metric_status', 'quality_state'],
    versionFields: ['versions', 'metric_dictionary_version'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['quality assessment missing', 'citation attribution cannot resolve canonical domain'],
  }),
  source({
    id: 'public.intelligence_mart_domain_page_feature_snapshots',
    category: 'audit',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_mart_domain_page_feature_snapshots',
    producers: ['supabase/migrations/064_intelligence_analytical_marts.sql'],
    consumers: ['feature trend APIs', 'intervention analysis', 'admin intelligence control room'],
    identityFields: ['scan_page_id', 'canonical_domain_id', 'canonical_page_id'],
    timestampFields: ['observed_at'],
    statusFields: ['eligible', 'metric_status', 'quality_state'],
    versionFields: ['metric_dictionary_version'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['legacy page lacks canonical identity', 'feature snapshot lacks extractor version'],
  }),
  source({
    id: 'public.intelligence_mart_intervention_outcomes',
    category: 'intervention',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_mart_intervention_outcomes',
    producers: ['supabase/migrations/064_intelligence_analytical_marts.sql'],
    consumers: ['outcome APIs', 'recommendation learning', 'admin intelligence control room'],
    identityFields: ['recommendation_id', 'canonical_domain_id'],
    timestampFields: ['approved_at', 'intervention_at', 'verified_at', 'before_observed_at', 'after_observed_at'],
    statusFields: ['eligible', 'metric_status', 'causality_label'],
    versionFields: ['metric_dictionary_version', 'comparison_label'],
    access: 'service_role',
    retention: 'product_record',
    knownFailureModes: ['no compatible post window', 'implementation not verified', 'association overstated as causation'],
  }),
  source({
    id: 'public.intelligence_retrieval_experiments',
    category: 'evaluation',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_retrieval_experiments',
    producers: ['scripts/intelligence-retrieval-experiment.ts'],
    consumers: ['admin intelligence patterns', 'retrieval go/no-go review'],
    identityFields: ['experiment_version', 'fixture_hash', 'provider', 'model', 'provider_version'],
    timestampFields: ['created_at'],
    statusFields: ['threshold_passed', 'recommendation'],
    versionFields: ['experiment_version', 'fixture_version', 'provider_version'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['evaluation fixture changed after indexing', 'unrepresentative labeled tasks', 'provider behavior drift'],
  }),
  source({
    id: 'public.intelligence_embedding_manifests',
    category: 'artifact',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_embedding_manifests',
    producers: ['bounded retrieval experiment'],
    consumers: ['retrieval experiment reconciliation'],
    identityFields: ['stable_embedding_id', 'evidence_id', 'source_text_hash'],
    timestampFields: ['embedded_at'],
    statusFields: ['visibility'],
    versionFields: ['provider', 'model', 'provider_version'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['source text changes without re-embedding', 'private evidence indexed without explicit scope'],
  }),
  source({
    id: 'public.intelligence_retrieval_task_results',
    category: 'evaluation',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_retrieval_task_results',
    producers: ['scripts/intelligence-retrieval-experiment.ts'],
    consumers: ['retrieval go/no-go review', 'admin intelligence patterns'],
    identityFields: ['experiment_id', 'task_id', 'retrieval_method'],
    timestampFields: ['created_at'],
    statusFields: ['access_correct'],
    versionFields: [],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['ranked IDs not recoverable', 'baseline and semantic filters differ'],
  }),
  source({
    id: 'public.intelligence_learning_patterns',
    category: 'evaluation',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_learning_patterns',
    producers: ['governed learning review'],
    consumers: ['methodology proposal review'],
    identityFields: ['id', 'pattern_key', 'metric_key'],
    timestampFields: ['created_at'],
    statusFields: ['status', 'quality_states', 'compatibility_label', 'causality_label'],
    versionFields: [],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['cohort drift', 'incompatible samples', 'correlation overstated as causation'],
  }),
  source({
    id: 'public.intelligence_methodology_proposals',
    category: 'configuration',
    authority: 'configuration',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_methodology_proposals',
    producers: ['governed learning review'],
    consumers: ['holdout evaluator', 'shadow evaluator', 'human methodology review'],
    identityFields: ['id', 'pattern_id', 'policy_kind', 'candidate_version'],
    timestampFields: ['created_at', 'updated_at', 'approved_at'],
    statusFields: ['status', 'holdout_passed', 'shadow_passed'],
    versionFields: ['candidate_version', 'previous_version'],
    access: 'service_role',
    retention: 'product_record',
    knownFailureModes: ['promotion without representative holdout', 'missing human approval', 'unclear rollback threshold'],
  }),
  source({
    id: 'public.intelligence_methodology_eval_links',
    category: 'evaluation',
    authority: 'derived_fact',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_methodology_eval_links',
    producers: ['holdout evaluator', 'shadow evaluator', 'regression evaluator'],
    consumers: ['methodology promotion gate', 'audit review'],
    identityFields: ['id', 'proposal_id', 'eval_run_id'],
    timestampFields: ['linked_at'],
    statusFields: ['evaluation_stage', 'passed'],
    versionFields: ['rubric_version', 'generator_version', 'source_snapshot'],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: ['eval source removed', 'source snapshot mismatch', 'lineage attached to wrong stage'],
  }),
  source({
    id: 'public.intelligence_policy_versions',
    category: 'configuration',
    authority: 'configuration',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_policy_versions',
    producers: ['methodology promotion and rollback'],
    consumers: ['scoring', 'recommendations', 'prompts', 'parsers', 'metric computation'],
    identityFields: ['id', 'policy_kind', 'policy_version', 'proposal_id'],
    timestampFields: ['created_at', 'activated_at', 'retired_at'],
    statusFields: ['status'],
    versionFields: ['policy_version', 'previous_policy_version'],
    access: 'service_role',
    retention: 'product_record',
    knownFailureModes: ['multiple active versions', 'consumer omits recorded version', 'rollback target unavailable'],
  }),
  source({
    id: 'public.intelligence_methodology_events',
    category: 'operations',
    authority: 'operational_log',
    storage: 'postgres',
    schema: 'public',
    table: 'intelligence_methodology_events',
    producers: ['governed learning transitions'],
    consumers: ['methodology audit', 'rollback review'],
    identityFields: ['id', 'proposal_id', 'actor_id'],
    timestampFields: ['created_at'],
    statusFields: ['from_status', 'to_status', 'actor_type'],
    versionFields: [],
    access: 'service_role',
    retention: 'product_record',
    knownFailureModes: ['missing transition reason', 'out-of-band policy change'],
  }),
  source({
    id: 'public.growth_campaigns',
    category: 'configuration',
    authority: 'configuration',
    storage: 'postgres',
    schema: 'public',
    table: 'growth_campaigns',
    producers: ['campaign chief of staff', 'migration 078'],
    consumers: ['Priya relevance gate', 'campaign control room', 'commercial intelligence'],
    identityFields: ['id', 'campaign_key', 'vertical', 'role'],
    timestampFields: ['created_at', 'updated_at', 'starts_at', 'ends_at'],
    statusFields: ['status', 'role'],
    versionFields: [],
    access: 'service_role',
    retention: 'product_record',
    knownFailureModes: [
      'multiple active campaigns in one role',
      'vertical allocation does not match operating strategy',
      'campaign outcome lacks subscription lineage',
    ],
  }),
  source({
    id: 'public.growth_campaign_interventions',
    category: 'operations',
    authority: 'configuration',
    storage: 'postgres',
    schema: 'public',
    table: 'growth_campaign_interventions',
    producers: ['campaign chief of staff', 'migration 078'],
    consumers: ['commercial outcome mart', 'governed learning', 'campaign control room'],
    identityFields: ['id', 'intervention_key', 'campaign_id'],
    timestampFields: ['created_at', 'updated_at', 'started_at', 'ended_at'],
    statusFields: ['status', 'channel'],
    versionFields: [],
    access: 'service_role',
    retention: 'measurement_history',
    knownFailureModes: [
      'multiple meaningful variables changed',
      'missing success or stop condition',
      'cross-vertical outcome blended without an explicit comparison',
    ],
  }),
] as const;

export function validateIntelligenceSourceRegistry(
  registry: readonly IntelligenceSourceDefinition[] = INTELLIGENCE_SOURCE_REGISTRY
): readonly string[] {
  const errors: string[] = [];
  const ids = new Set<string>();
  for (const item of registry) {
    if (ids.has(item.id)) errors.push(`duplicate source id: ${item.id}`);
    ids.add(item.id);
    if (item.storage === 'postgres' && (!item.schema || !item.table)) {
      errors.push(`postgres source missing schema/table: ${item.id}`);
    }
    if (item.storage !== 'postgres' && !item.artifactKind) {
      errors.push(`non-postgres source missing artifactKind: ${item.id}`);
    }
    if (item.producers.length === 0) errors.push(`source has no producer: ${item.id}`);
    if (item.consumers.length === 0) errors.push(`source has no consumer: ${item.id}`);
  }
  return errors;
}

export function postgresIntelligenceSources(
  registry: readonly IntelligenceSourceDefinition[] = INTELLIGENCE_SOURCE_REGISTRY
): readonly PostgresIntelligenceSource[] {
  return registry.filter(
    (item): item is PostgresIntelligenceSource =>
      item.storage === 'postgres' && Boolean(item.schema) && Boolean(item.table)
  );
}
