/**
 * Wraps the OpenNext worker so we can handle Cloudflare Queues on the same Worker.
 * Build artifact: run `npm run build:worker` before `wrangler deploy` / `wrangler dev`.
 */
// @ts-ignore — `.open-next/worker.js` is generated by opennextjs-cloudflare build (not in tsc graph)
import openNextWorker from '../.open-next/worker.js';
import { dispatchQueueBatch, type ReportQueueBatch } from './queue/report-queue-consumer';
import { sendWeeklyReport } from '../services/marketing-attribution/weekly-report';
import { createClient } from '@supabase/supabase-js';
import { structuredError } from '../lib/server/structured-log';
import { createBenchmarkExecutionAdapter } from '../lib/server/benchmark-execution';
import { runScheduledBenchmarkSweep } from '../lib/server/benchmark-schedule';

const next = openNextWorker as {
  fetch: (request: Request, env: CloudflareEnv, ctx: ExecutionContext) => Promise<Response>;
};

async function pingSupabaseKeepAlive(env: CloudflareEnv): Promise<void> {
  const base = env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/, '') ?? '';
  const key = env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? '';
  if (!base || !key) {
    return;
  }
  const res = await fetch(`${base}/rest/v1/`, {
    headers: {
      apikey: key,
      Authorization: `Bearer ${key}`,
    },
  });
  if (!res.ok) {
    structuredError('supabase_keepalive_failed', { status: res.status });
  }
}

export default {
  fetch: next.fetch.bind(next),

  async queue(batch: ReportQueueBatch, env: CloudflareEnv, _ctx: ExecutionContext): Promise<void> {
    await dispatchQueueBatch(batch, env);
  },

  async scheduled(_event: ScheduledEvent, env: CloudflareEnv, _ctx: ExecutionContext): Promise<void> {
    try {
      await pingSupabaseKeepAlive(env);
    } catch {
      structuredError('supabase_keepalive_error', {});
    }

    const isMonday = new Date().getUTCDay() === 1;
    const reportTo = (env as unknown as Record<string, string>)['MARKETING_REPORT_TO'] ?? '';
    const resendKey = (env as unknown as Record<string, string>)['RESEND_API_KEY'] ?? '';
    const resendFrom = (env as unknown as Record<string, string>)['RESEND_FROM_EMAIL'] ?? '';
    const supaUrl = env.NEXT_PUBLIC_SUPABASE_URL ?? '';
    const supaKey = (env as unknown as Record<string, string>)['SUPABASE_SERVICE_ROLE_KEY'] ?? '';

    if (isMonday && reportTo && resendKey && resendFrom && supaUrl && supaKey) {
      try {
        const supabase = createClient(supaUrl, supaKey, {
          auth: { persistSession: false, autoRefreshToken: false },
        });
        const result = await sendWeeklyReport({
          supabase,
          resendApiKey: resendKey,
          from: resendFrom,
          to: reportTo,
        });
        if (!result.ok) {
          structuredError('weekly_report_failed', { reason: result.reason });
        }
      } catch (err) {
        structuredError('weekly_report_error', {
          error: err instanceof Error ? err.message : 'unknown',
        });
      }
    }

    if (supaUrl && supaKey) {
      try {
        const supabase = createClient(supaUrl, supaKey, {
          auth: { persistSession: false, autoRefreshToken: false },
        });
        await runScheduledBenchmarkSweep({
          supabase,
          env,
          adapter: createBenchmarkExecutionAdapter(env),
        });
      } catch (err) {
        structuredError('benchmark_schedule_worker_error', {
          error: err instanceof Error ? err.message : 'unknown',
        });
      }
    }
  },
};
