/**
 * Wraps the OpenNext worker so we can handle Cloudflare Queues on the same Worker.
 * Build artifact: run `npm run build:worker` before `wrangler deploy` / `wrangler dev`.
 */
// @ts-ignore — `.open-next/worker.js` is generated by opennextjs-cloudflare build (not in tsc graph)
import openNextWorker from '../.open-next/worker.js';
import { dispatchQueueBatch, type ReportQueueBatch } from './queue/report-queue-consumer';
import { dispatchDistributionQueueBatch } from './queue/distribution-job-queue-consumer';
import { sendWeeklyReport } from '../services/marketing-attribution/weekly-report';
import { createClient } from '@supabase/supabase-js';
import { structuredError, structuredLog } from '../lib/server/structured-log';
import { createBenchmarkExecutionAdapter } from '../lib/server/benchmark-execution';
import { runScheduledBenchmarkSweep } from '../lib/server/benchmark-schedule';
import { runScheduledDistributionDispatch } from '../lib/server/distribution-job-schedule';
import { runScheduledStartupExecutionDispatch } from '../lib/server/startup-execution-dispatch-schedule';
import { runScheduledStartupSlackAutoPost } from '../lib/server/startup-slack-schedule';
import { runGpmScheduledSweep } from '../lib/server/geo-performance-schedule';
import { buildGpmEntitlementsMap } from '../lib/server/geo-performance-entitlements';
import {
  fetchAndBuildBenchmarkDailyRecap,
  sendBenchmarkDailyRecap,
} from '../lib/server/benchmark-daily-recap';

const next = openNextWorker as {
  fetch: (request: Request, env: CloudflareEnv, ctx: ExecutionContext) => Promise<Response>;
};

function applyDefaultSecurityHeaders(response: Response): Response {
  const headers = new Headers(response.headers);
  const defaults = {
    'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'DENY',
  } as const;

  for (const [key, value] of Object.entries(defaults)) {
    if (!headers.has(key)) {
      headers.set(key, value);
    }
  }

  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

async function pingSupabaseKeepAlive(env: CloudflareEnv): Promise<void> {
  const base = env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/, '') ?? '';
  const key = env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? '';
  if (!base || !key) {
    return;
  }
  const res = await fetch(`${base}/rest/v1/`, {
    headers: {
      apikey: key,
      Authorization: `Bearer ${key}`,
    },
  });
  if (!res.ok) {
    structuredError('supabase_keepalive_failed', { status: res.status });
  }
}

export default {
  async fetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext): Promise<Response> {
    const response = await next.fetch(request, env, ctx);
    return applyDefaultSecurityHeaders(response);
  },

  async queue(batch: ReportQueueBatch, env: CloudflareEnv, _ctx: ExecutionContext): Promise<void> {
    if (
      batch.queue === 'geo-pulse-distribution-queue' ||
      batch.queue === 'geo-pulse-distribution-dlq'
    ) {
      await dispatchDistributionQueueBatch(batch as any, env);
      return;
    }

    await dispatchQueueBatch(batch, env);
  },

  async scheduled(_event: ScheduledEvent, env: CloudflareEnv, _ctx: ExecutionContext): Promise<void> {
    try {
      await pingSupabaseKeepAlive(env);
    } catch {
      structuredError('supabase_keepalive_error', {});
    }

    const isMonday = new Date().getUTCDay() === 1;
    const reportTo = (env as unknown as Record<string, string>)['MARKETING_REPORT_TO'] ?? '';
    const resendKey = (env as unknown as Record<string, string>)['RESEND_API_KEY'] ?? '';
    const resendFrom = (env as unknown as Record<string, string>)['RESEND_FROM_EMAIL'] ?? '';
    const supaUrl = env.NEXT_PUBLIC_SUPABASE_URL ?? '';
    const supaKey = (env as unknown as Record<string, string>)['SUPABASE_SERVICE_ROLE_KEY'] ?? '';

    if (isMonday && reportTo && resendKey && resendFrom && supaUrl && supaKey) {
      try {
        const supabase = createClient(supaUrl, supaKey, {
          auth: { persistSession: false, autoRefreshToken: false },
        });
        const result = await sendWeeklyReport({
          supabase,
          resendApiKey: resendKey,
          from: resendFrom,
          to: reportTo,
        });
        if (!result.ok) {
          structuredError('weekly_report_failed', { reason: result.reason });
        }
      } catch (err) {
        structuredError('weekly_report_error', {
          error: err instanceof Error ? err.message : 'unknown',
        });
      }
    }

    if (supaUrl && supaKey) {
      try {
        const supabase = createClient(supaUrl, supaKey, {
          auth: { persistSession: false, autoRefreshToken: false },
        });
        await runScheduledBenchmarkSweep({
          supabase,
          env,
          adapter: createBenchmarkExecutionAdapter(env),
          triggerSource: 'worker_cron',
        });
      } catch (err) {
        structuredError('benchmark_schedule_worker_error', {
          error: err instanceof Error ? err.message : 'unknown',
        });
      }

      try {
        const supabase = createClient(supaUrl, supaKey, {
          auth: { persistSession: false, autoRefreshToken: false },
        });
        await runScheduledDistributionDispatch(supabase as any, env as any);
      } catch (err) {
        structuredError('distribution_schedule_worker_error', {
          error: err instanceof Error ? err.message : 'unknown',
        });
      }

      try {
        const supabase = createClient(supaUrl, supaKey, {
          auth: { persistSession: false, autoRefreshToken: false },
        });
        await runScheduledStartupSlackAutoPost({
          supabase: supabase as any,
          env: env as any,
        });
      } catch (err) {
        structuredError('startup_slack_schedule_worker_error', {
          error: err instanceof Error ? err.message : 'unknown',
        });
      }

      try {
        const supabase = createClient(supaUrl, supaKey, {
          auth: { persistSession: false, autoRefreshToken: false },
        });
        await runScheduledStartupExecutionDispatch({
          supabase: supabase as any,
          env: env as any,
        });
      } catch (err) {
        structuredError('startup_execution_dispatch_worker_error', {
          error: err instanceof Error ? err.message : 'unknown',
        });
      }

      try {
        const supabase = createClient(supaUrl, supaKey, {
          auth: { persistSession: false, autoRefreshToken: false },
        });
        const envRecord = env as unknown as Record<string, string | undefined>;
        const gpmEnv = {
          GPM_SCHEDULE_ENABLED:    envRecord['GPM_SCHEDULE_ENABLED'],
          GPM_CHATGPT_MODEL_ID:    envRecord['GPM_CHATGPT_MODEL_ID'],
          GPM_GEMINI_MODEL_ID:     envRecord['GPM_GEMINI_MODEL_ID'],
          GPM_PERPLEXITY_MODEL_ID: envRecord['GPM_PERPLEXITY_MODEL_ID'],
          GPM_ENABLED_PLATFORMS:   envRecord['GPM_ENABLED_PLATFORMS'],
          ANTHROPIC_API_KEY:       envRecord['ANTHROPIC_API_KEY'],
          GPM_NARRATIVE_MODEL:     envRecord['GPM_NARRATIVE_MODEL'],
          // Gemini narrative fallback (used when no ANTHROPIC_API_KEY). Falls back to
          // the benchmark Gemini key so the narrative works with zero extra config.
          GEMINI_API_KEY:          envRecord['GEMINI_API_KEY'] ?? envRecord['BENCHMARK_EXECUTION_API_KEY'],
          GPM_NARRATIVE_GEMINI_MODEL: envRecord['GPM_NARRATIVE_GEMINI_MODEL'],
          GEMINI_ENDPOINT:         envRecord['GEMINI_ENDPOINT'],
          GPM_REPORT_R2_PUBLIC_BASE: envRecord['GPM_REPORT_R2_PUBLIC_BASE'],
          RESEND_API_KEY:          resendKey || undefined,
          RESEND_FROM_EMAIL:       resendFrom || undefined,
        };
        const { data: configStubs } = await supabase
          .from('client_benchmark_configs')
          .select('id, startup_workspace_id, agency_account_id');
        const entitlementsMap = await buildGpmEntitlementsMap(supabase, configStubs ?? []);
        await runGpmScheduledSweep({
          supabase,
          env: gpmEnv,
          entitlementsByConfigId: entitlementsMap,
          adapter: createBenchmarkExecutionAdapter(env),
          triggerSource: 'worker_cron',
          reportBucket: (env as any).REPORT_FILES,
        });
      } catch (err) {
        structuredError('gpm_schedule_worker_error', {
          error: err instanceof Error ? err.message : 'unknown',
        });
      }

      // Daily benchmark recap email — gated to a single cron tick per day so the
      // noon and midnight runs don't both fire. Skipped when no recipient or
      // Resend key is configured.
      const envRecord = env as unknown as Record<string, string | undefined>;
      const recapTo = envRecord['BENCHMARK_DAILY_RECAP_TO'];
      const recapHourRaw = envRecord['BENCHMARK_DAILY_RECAP_HOUR_UTC'];
      const recapHour = Number.parseInt(recapHourRaw ?? '0', 10);
      const recapHourGate = Number.isFinite(recapHour) ? recapHour : 0;
      const recapVertical = envRecord['BENCHMARK_SCHEDULE_VERTICAL'] ?? 'marketing_firms';
      const nowUtcHour = new Date().getUTCHours();

      if (recapTo && resendKey && resendFrom && nowUtcHour === recapHourGate) {
        try {
          const supabase = createClient(supaUrl, supaKey, {
            auth: { persistSession: false, autoRefreshToken: false },
          });
          const recap = await fetchAndBuildBenchmarkDailyRecap({
            supabase,
            vertical: recapVertical,
            now: new Date(),
          });
          const result = await sendBenchmarkDailyRecap({
            recap,
            resendApiKey: resendKey,
            from: resendFrom,
            to: recapTo,
          });
          if (!result.ok) {
            structuredError('benchmark_daily_recap_send_failed', { reason: result.reason });
          } else {
            structuredLog('benchmark_daily_recap_sent', {
              to: recapTo,
              vertical: recapVertical,
              completed_runs: recap.runStatus.completed,
              failed_runs: recap.runStatus.failed,
              total_citations: recap.totalCitations,
              cited_domains: recap.distinctDomainsCited,
            });
          }
        } catch (err) {
          structuredError('benchmark_daily_recap_error', {
            error: err instanceof Error ? err.message : 'unknown',
          });
        }
      }
    }
  },
};
