/**
 * Wraps the OpenNext worker so we can handle Cloudflare Queues on the same Worker.
 * Build artifact: run `npm run build:worker` before `wrangler deploy` / `wrangler dev`.
 */
// @ts-ignore — `.open-next/worker.js` is generated by opennextjs-cloudflare build (not in tsc graph)
import openNextWorker from '../.open-next/worker.js';
import { dispatchQueueBatch, type ReportQueueBatch } from './queue/report-queue-consumer';

const next = openNextWorker as {
  fetch: (request: Request, env: CloudflareEnv, ctx: ExecutionContext) => Promise<Response>;
};

export default {
  fetch: next.fetch.bind(next),

  async queue(batch: ReportQueueBatch, env: CloudflareEnv, _ctx: ExecutionContext): Promise<void> {
    await dispatchQueueBatch(batch, env);
  },
};
